### ISSUE TITLE
Checkbox's third state isn't being saved persistently

### ISSUE THREAD

**Issue by BoopyTheFox** [NovaGaia/obsidian-checkbox3states-plugin#2]
**Expected behavior**
When i shift+click (or long tap on mobile) a checkbox in Live Preview mode, third state is set, and checkbox is changed to "- [/]". 
When i close page and open it again, checkbox state is still "- [/]" and third state is displayed in Live Preview mode by the plugin.

**Current behavior**
When i shift+click (or long tap) a checkbox, third state is set and is visible in Live Preview, but checkbox is not changed 
(it stays either "- [ ]" or "- [x]", depending on previous state).
This causes plugin to only show third state in Live Preview until page is reloaded, after which it is changed back to previous state.

**Reproducible** - always

**Versions**
Plugin - 1.1.5
Obsidian - 1.1.7, 1.1.8, 1.1.9 for sure, haven't tested on other ones.

Workaround - manually type "- [/]" in source mode, this makes checkbox state persist between reloads, and is displayed on Live Preview mode correctly.

**Comment by Legendsmith** [comment]
I am also experiencing this issue, (and the workaround also works).

**Comment by BoopyTheFox** [comment]
I've resorted to use themes that render multiple checkbox states ( [ ], [x], [/], [-], [<], [>] )
They don't require an addon. I enter states manually.

Examples - Blue Topaz, Sanctum, Things, Minimal

**Comment by TimTheBig** [comment]
If you just want multiple checkbox states without the rest of the theme have a look at [minimal-checklists](https://github.com/HuangZhuo/minimal-checklists).

**Comment by nonchip** [comment]
so just to double check, the *only* usecase of this plugin is "not planned"? might wanna take it off the plugin list then.
